fragment AssetDetail on Asset {
  id
  chainId
  collectionAddress
  tokenId
  name
  collection {
    chainId
    address
    name
  }
  image
  animationUrl
  unlockedContent {
    url
    mimetype
  }
  auctions(
    first: 1
    orderBy: CREATED_AT_DESC
    filter: { endAt: { greaterThan: $now } }
  ) {
    nodes {
      id
      endAt
      bestBid: offers(
        orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
        first: 1
        filter: {
          signature: { isNull: false }
          expiredAt: { greaterThan: $now }
        }
      ) {
        nodes {
          unitPrice
          amount
          currency {
            decimals
            symbol
          }
        }
      }
    }
  }
  bestBid: bids(
    orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
    filter: { expiredAt: { greaterThan: $now } }
    first: 1
  ) {
    nodes {
      unitPrice
      amount
      currency {
        image
        name
        id
        decimals
        symbol
      }
    }
  }
  firstSale: sales(
    first: 1
    orderBy: [UNIT_PRICE_IN_REF_ASC, CREATED_AT_ASC]
    filter: { expiredAt: { greaterThan: $now } }
  ) {
    totalCount
    totalCurrencyDistinctCount
    nodes {
      id
      unitPrice
      currency {
        image
        id
        decimals
        symbol
      }
    }
  }
  creator {
    address
    name
    image
    verification {
      status
    }
  }
  owned: ownership(ownerAddress: $currentAddress) {
    quantity
  }
}
