query FetchCreatedAssets(
  $address: Address!
  $currentAddress: Address!
  $now: Datetime!
  $limit: Int!
  $offset: Int!
  $orderBy: [AssetsOrderBy!]
) {
  created: assets(
    filter: { ownershipsExist: true, creatorAddress: { equalTo: $address } }
    first: $limit
    offset: $offset
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      ...AssetDetail
    }
  }
}
