query FetchOnSaleAssets(
  $address: Address!
  $currentAddress: Address!
  $now: Datetime!
  $limit: Int!
  $offset: Int!
  $orderBy: [AssetsOrderBy!]
) {
  onSale: assets(
    filter: {
      ownershipsExist: true
      or: [
        {
          sales: {
            some: {
              expiredAt: { greaterThan: $now }
              makerAddress: { equalTo: $address }
            }
          }
        }
        {
          auctions: {
            some: {
              endAt: { greaterThan: $now }
              creatorAddress: { equalTo: $address }
            }
          }
        }
      ]
    }
    first: $limit
    offset: $offset
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      ...AssetDetail
    }
  }
}
