query FetchDefaultAssetIds($limit: Int!) {
  assets(orderBy: CREATED_AT_DESC, first: $limit) {
    nodes {
      chainId
      collectionAddress
      tokenId
    }
  }
}

query FetchAssets(
  $limit: Int!
  $ids: [AssetIdsCondition!]!
  $address: Address
) {
  assets(condition: { ids: $ids }, first: $limit) {
    nodes {
      chainId
      collectionAddress
      tokenId
      name
      collection {
        chainId
        address
        name
        standard
      }
      quantity
      image
      imageMimetype
      creator {
        address
        name
        image
        verification {
          status
        }
      }
      owned: ownership(ownerAddress: $address) {
        quantity
      }
      bestBid {
        unitPrice
        amount
        currency {
          image
          name
          id
          decimals
          symbol
        }
      }
      firstSale {
        id
        unitPrice
        currency {
          image
          name
          id
          decimals
          symbol
        }
        maker {
          address
        }
      }
      totalSalesCount
      totalSalesCurrencyDistinctCount
    }
  }
}
