query FetchCollections($filter: CollectionFilter!, $limit: Int!) {
  collections(filter: $filter, first: $limit, orderBy: TOTAL_VOLUME_DESC) {
    nodes {
      chainId
      address
      name
      image
      cover
      description
      totalVolume {
        refCode
        valueInRef
      }
      floorPrice {
        refCode
        valueInRef
      }
    }
  }
}
