query FetchAccountAndCollection(
  $account: Address!
  $chainId: Int!
  $collectionAddress: Address!
) {
  account(address: $account) {
    address
    name
    image
    verification {
      status
    }
  }
  collection(chainId: $chainId, address: $collectionAddress) {
    chainId
    address
    name
    standard
  }
}
