query FetchAssetBids($id: String!, $now: Datetime!) {
  asset(id: $id) {
    bids(
      orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
      filter: { expiredAt: { greaterThan: $now } }
    ) {
      nodes {
        id
        createdAt
        expiredAt
        availableQuantity
        taker {
          address
        }
        maker {
          address
          name
          image
          verification {
            status
          }
        }
        amount
        unitPrice
        currency {
          image
          name
          id
          decimals
          symbol
        }
      }
    }
  }
}

query FetchAuctionBids($auctionId: UUID!, $now: Datetime!) {
  auction(id: $auctionId) {
    offers(
      orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
      filter: { signature: { isNull: false }, expiredAt: { greaterThan: $now } }
    ) {
      nodes {
        id
        createdAt
        expiredAt
        availableQuantity
        taker {
          address
        }
        maker {
          address
          name
          image
          verification {
            status
          }
        }
        amount
        unitPrice
        currency {
          image
          name
          id
          decimals
          symbol
        }
      }
    }
  }
}
