query FetchAssetBids(
  $chainId: Int!
  $collectionAddress: Address!
  $tokenId: String!
  $now: Datetime!
) {
  asset(
    chainId: $chainId
    collectionAddress: $collectionAddress
    tokenId: $tokenId
  ) {
    chainId
    collectionAddress
    tokenId
    bids(
      orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
      filter: { expiredAt: { greaterThan: $now } }
      first: 100 # TODO: implement pagination
    ) {
      nodes {
        id
        createdAt
        expiredAt
        availableQuantity
        taker {
          address
        }
        maker {
          address
          name
          image
          verification {
            status
          }
        }
        amount
        unitPrice
        currency {
          image
          name
          id
          decimals
          symbol
        }
      }
    }
  }
}

query FetchAuctionBids($auctionId: UUID!, $now: Datetime!) {
  auction(id: $auctionId) {
    offers(
      orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
      filter: { signature: { isNull: false }, expiredAt: { greaterThan: $now } }
      first: 100 # TODO: implement pagination
    ) {
      nodes {
        id
        createdAt
        expiredAt
        availableQuantity
        taker {
          address
        }
        maker {
          address
          name
          image
          verification {
            status
          }
        }
        amount
        unitPrice
        currency {
          image
          name
          id
          decimals
          symbol
        }
      }
    }
  }
}
