query FetchUserBidsPlaced(
  $limit: Int!
  $offset: Int!
  $orderBy: [OfferOpenBuysOrderBy!]
  $address: Address!
  $now: Datetime
) {
  account(address: $address) {
    ...AccountDetail
  }
  created: assets(
    filter: { ownershipsExist: true, creatorAddress: { equalTo: $address } }
  ) {
    totalCount
  }
  onSale: assets(
    filter: {
      ownershipsExist: true
      or: [
        {
          sales: {
            some: {
              expiredAt: { greaterThan: $now }
              makerAddress: { equalTo: $address }
              availableQuantity: { greaterThan: "0" }
            }
          }
        }
        {
          auctions: {
            some: {
              endAt: { greaterThan: $now }
              creatorAddress: { equalTo: $address }
            }
          }
        }
      ]
    }
  ) {
    totalCount
  }
  owned: ownerships(
    filter: { ownerAddress: { equalTo: $address }, assetExists: true }
  ) {
    totalCount
  }
  bids: offerOpenBuys(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    filter: { makerAddress: { equalTo: $address } }
  ) {
    totalCount
    nodes {
      id
      unitPrice
      amount
      availableQuantity
      expiredAt
      createdAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      currency {
        image
        name
        id
        decimals
        symbol
      }
      asset {
        id
        name
        image
        chainId
      }
    }
  }
}
