query FetchUserBidsPlaced(
  $limit: Int!
  $offset: Int!
  $orderBy: [OfferOpenBuysOrderBy!]
  $address: Address!
) {
  bids: offerOpenBuys(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    filter: { makerAddress: { equalTo: $address } }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      id
      unitPrice
      amount
      availableQuantity
      expiredAt
      createdAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      currency {
        image
        name
        id
        decimals
        symbol
      }
      asset {
        id
        chainId
        collectionAddress
        tokenId
        name
        image
      }
    }
  }
}
