query FetchUserBidsPlaced(
  $limit: Int!
  $offset: Int!
  $orderBy: [OffersOrderBy!]
  $address: Address!
) {
  bids: openOffers(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    condition: { status: ACTIVE, makerAddress: $address }
    includeWhenAssetDeleted: YES
    includeWhenCurrencyDeleted: YES
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      id
      unitPrice
      amount
      availableQuantity
      expiredAt
      createdAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      currency {
        image
        name
        id
        decimals
        symbol
      }
      asset {
        chainId
        collectionAddress
        tokenId
        name
        image
        imageMimetype
        deletedAt
      }
    }
  }
}
