query FetchUserBidsReceived(
  $limit: Int!
  $offset: Int!
  $orderBy: [OfferOpenBuysOrderBy!]
  $address: Address!
  $now: Datetime
) {
  bids: offerOpenBuys(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    filter: {
      expiredAt: { greaterThan: $now }
      makerAddress: { notEqualTo: $address }
      asset: { ownerships: { some: { ownerAddress: { equalTo: $address } } } }
    }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      id
      amount
      unitPrice
      availableQuantity
      expiredAt
      createdAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      currency {
        image
        name
        id
        decimals
        symbol
      }
      asset {
        id
        chainId
        collectionAddress
        tokenId
        name
        image
      }
    }
  }
}
