query FetchCartItems($offerIds: [UUID!]!) {
  offerOpenSales(filter: { id: { in: $offerIds } }) {
    nodes {
      id
      type
      expiredAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      unitPrice
      availableQuantity
      currency {
        image
        id
        decimals
        symbol
      }
      asset {
        id
        chainId
        collectionAddress
        tokenId
        collection {
          chainId
          address
          name
          standard
        }
        name
        image
        imageMimetype
        unlockedContent {
          url
          mimetype
        }
        animationUrl
        animationMimetype
      }
    }
  }
}
