query FetchUserFixedPrice(
  $limit: Int!
  $offset: Int!
  $orderBy: [OffersOrderBy!]
  $address: Address!
  $now: Datetime
) {
  account(address: $address) {
    ...AccountDetail
  }
  created: assets(
    filter: { ownershipsExist: true, creatorAddress: { equalTo: $address } }
  ) {
    totalCount
  }
  onSale: assets(
    filter: {
      ownershipsExist: true
      or: [
        {
          sales: {
            some: {
              expiredAt: { greaterThan: $now }
              makerAddress: { equalTo: $address }
              availableQuantity: { greaterThan: "0" }
            }
          }
        }
        {
          auctions: {
            some: {
              endAt: { greaterThan: $now }
              creatorAddress: { equalTo: $address }
            }
          }
        }
      ]
    }
  ) {
    totalCount
  }
  owned: ownerships(
    filter: { ownerAddress: { equalTo: $address }, assetExists: true }
  ) {
    totalCount
  }
  offers: offers(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    filter: {
      type: { equalTo: SALE }
      signature: { isNull: false }
      makerAddress: { equalTo: $address }
    }
  ) {
    totalCount
    nodes {
      id
      unitPrice
      availableQuantity
      expiredAt
      createdAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      asset {
        id
        name
        image
        chainId
        ownerships(filter: { ownerAddress: { equalTo: $address } }) {
          aggregates {
            sum {
              quantity
            }
          }
        }
      }
      currency {
        id
        name
        image
        id
        decimals
        symbol
      }
    }
  }
}
