query FetchUserFixedPrice(
  $limit: Int!
  $offset: Int!
  $orderBy: [OffersOrderBy!]
  $address: Address!
) {
  offers: offers(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    filter: {
      type: { equalTo: SALE }
      signature: { isNull: false }
      makerAddress: { equalTo: $address }
    }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      id
      unitPrice
      availableQuantity
      expiredAt
      createdAt
      maker {
        address
        name
        image
        verification {
          status
        }
      }
      asset {
        id
        chainId
        collectionAddress
        tokenId
        name
        image
        owned: ownership(ownerAddress: $address) {
          quantity
        }
      }
      currency {
        id
        name
        image
        decimals
        symbol
      }
    }
  }
}
