query FetchAsset(
  $chainId: Int!
  $collectionAddress: Address!
  $tokenId: String!
  $address: Address
  $now: Datetime!
) {
  asset(
    chainId: $chainId
    collectionAddress: $collectionAddress
    tokenId: $tokenId
  ) {
    id
    tokenId
    tokenUri
    chainId
    collectionAddress
    collection {
      chainId
      name
      address
      standard
      supply
      mintType
    }
    name
    description
    traits(
      orderBy: TYPE_ASC
      first: 100 # TODO: implement pagination
    ) {
      nodes {
        type
        value
        collectionTraitValue {
          numberOfAssets
        }
      }
    }
    quantity
    image
    animationUrl
    hasUnlockableContent
    unlockedContent {
      url
      mimetype
    }
    creator {
      address
      name
      image
      verification {
        status
      }
    }
    bestBid: bids(
      orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
      filter: { expiredAt: { greaterThan: $now } }
      first: 1
    ) {
      nodes {
        unitPrice
        amount
        currency {
          image
          name
          id
          decimals
          symbol
        }
      }
    }
    owned: ownership(ownerAddress: $address) {
      quantity
    }
    ownerships(
      orderBy: [
        QUANTITY_DESC
        ACCOUNT_BY_OWNER_ADDRESS__NAME_ASC
        OWNER_ADDRESS_ASC
      ]
      first: 5
    ) {
      totalCount
      nodes {
        ownerAddress
        quantity
        owner {
          address
          name
          image
          verification {
            status
          }
        }
      }
    }
    sales(
      orderBy: [UNIT_PRICE_IN_REF_ASC, CREATED_AT_ASC]
      filter: { expiredAt: { greaterThan: $now } }
      first: 100 # TODO: implement pagination
    ) {
      nodes {
        id
        unitPrice
        expiredAt
        availableQuantity
        currency {
          image
          name
          id
          decimals
          symbol
        }
        maker {
          image
          address
          name
          verification {
            status
          }
        }
      }
      totalAvailableQuantitySum
    }
    auctions(first: 1, orderBy: CREATED_AT_DESC) {
      nodes {
        id
        endAt
        expireAt
        reserveAmount
        winningOffer {
          id
        }
        currency {
          image
          decimals
          symbol
        }
        offers(
          orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
          filter: { signature: { isNull: false } }
          first: 1
        ) {
          nodes {
            id
            createdAt
            expiredAt
            availableQuantity
            taker {
              address
            }
            maker {
              address
              name
              image
              verification {
                status
              }
            }
            amount
            unitPrice
            currency {
              image
              name
              id
              decimals
              symbol
            }
          }
        }
      }
    }
  }
}
