query FetchCollectionsForMint {
  collections(
    filter: { mintType: { equalTo: PUBLIC } }
    orderBy: CREATED_AT_ASC
  ) {
    nodes {
      chainId
      address
      standard
      image
      name
    }
  }
}
