mutation CreateCartPurchaseTransaction(
  $accountAddress: Address!
  $items: [CreateCheckoutTransactionItemInput!]!
) {
  createCheckoutTransaction(accountAddress: $accountAddress, items: $items) {
    transaction {
      to
      from
      data
      gasPrice
      value
    }
  }
}
