query Checkout($id: UUID!, $address: Address, $now: Datetime!) {
  offer(id: $id) {
    id
    type
    maker {
      address
      name
      image
      verification {
        status
      }
    }
    asset {
      id
      collection {
        chainId
        address
        name
        standard
      }
      name
      image
      unlockedContent {
        url
        mimetype
      }
      animationUrl
      creator {
        address
        name
        image
        verification {
          status
        }
      }
      owned: ownerships(filter: { ownerAddress: { equalTo: $address } }) {
        aggregates {
          sum {
            quantity
          }
        }
      }
      bestBid: bids(
        orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
        filter: { expiredAt: { greaterThan: $now } }
        first: 1
      ) {
        nodes {
          unitPrice
          amount
          currency {
            image
            name
            id
            decimals
            symbol
          }
        }
      }
      firstSale: sales(
        first: 1
        orderBy: [UNIT_PRICE_IN_REF_ASC, CREATED_AT_ASC]
        filter: { expiredAt: { greaterThan: $now } }
      ) {
        totalCount
        nodes {
          id
          unitPrice
          currency {
            image
            name
            id
            decimals
            symbol
          }
        }
      }
      currencySales: sales(filter: { expiredAt: { greaterThan: $now } }) {
        aggregates {
          distinctCount {
            currencyId
          }
        }
      }
      auctions(
        first: 1
        orderBy: CREATED_AT_DESC
        filter: { endAt: { greaterThan: $now } }
      ) {
        nodes {
          id
          endAt
          bestBid: offers(
            orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
            first: 1
            filter: { signature: { isNull: false } }
          ) {
            nodes {
              unitPrice
              amount
              currency {
                decimals
                symbol
              }
            }
          }
        }
      }
    }
    unitPrice
    availableQuantity
    currency {
      image
      id
      decimals
      symbol
    }
  }
}
