query Checkout($id: UUID!, $address: Address, $now: Datetime!) {
  offer(id: $id) {
    id
    type
    asset {
      chainId
      collectionAddress
      tokenId
      id
      deletedAt
      collection {
        chainId
        address
        name
        standard
      }
      name
      image
      imageMimetype
      creator {
        address
        name
        image
        verification {
          status
        }
      }
      owned: ownership(ownerAddress: $address) {
        quantity
      }
      quantity
      bestBid: bids(
        orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
        filter: { expiredAt: { greaterThan: $now } }
        first: 1
      ) {
        nodes {
          unitPrice
          amount
          currency {
            image
            name
            id
            decimals
            symbol
          }
        }
      }
      firstSale: sales(
        first: 1
        orderBy: [UNIT_PRICE_IN_REF_ASC, CREATED_AT_ASC]
        filter: { expiredAt: { greaterThan: $now } }
      ) {
        totalCount
        totalCurrencyDistinctCount
        nodes {
          id
          unitPrice
          currency {
            image
            name
            id
            decimals
            symbol
          }
        }
      }
    }
    maker {
      address
      name
      image
      verification {
        status
      }
    }
    unitPrice
    availableQuantity
    currency {
      image
      id
      decimals
      symbol
      deletedAt
    }
  }
}
