query FetchExploreCollections(
  $limit: Int!
  $offset: Int!
  $orderBy: [CollectionsOrderBy!]
  $filter: [CollectionFilter!]
) {
  collections(
    first: $limit
    offset: $offset
    orderBy: $orderBy
    filter: { and: $filter }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      chainId
      address
      name
      image
      cover
      description
      totalVolume {
        refCode
        valueInRef
      }
      floorPrice {
        refCode
        valueInRef
      }
    }
  }
}
