query FetchAllERC721And1155(
  $now: Datetime!
  $address: Address
  $limit: Int!
  $offset: Int!
  $orderBy: [AssetsOrderBy!]
  $filter: [AssetFilter!]
) {
  assets(
    filter: { and: $filter }
    first: $limit
    offset: $offset
    orderBy: $orderBy
  ) {
    totalCount
    nodes {
      id
      name
      collection {
        chainId
        address
        name
      }
      image
      unlockedContent {
        url
        mimetype
      }
      animationUrl
      owned: ownerships(filter: { ownerAddress: { equalTo: $address } }) {
        aggregates {
          sum {
            quantity
          }
        }
      }
      auctions(
        first: 1
        orderBy: CREATED_AT_DESC
        filter: { endAt: { greaterThan: $now } }
      ) {
        nodes {
          id
          endAt
          bestBid: offers(
            orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
            first: 1
            filter: { signature: { isNull: false } }
          ) {
            nodes {
              unitPrice
              amount
              currency {
                image
                name
                id
                decimals
                symbol
              }
            }
          }
        }
      }
      bestBid: bids(
        orderBy: [UNIT_PRICE_IN_REF_DESC, CREATED_AT_ASC]
        filter: { expiredAt: { greaterThan: $now } }
        first: 1
      ) {
        nodes {
          unitPrice
          amount
          currency {
            image
            name
            id
            decimals
            symbol
          }
        }
      }
      firstSale: sales(
        first: 1
        orderBy: [UNIT_PRICE_IN_REF_ASC, CREATED_AT_ASC]
        filter: {
          expiredAt: { greaterThan: $now }
          availableQuantity: { greaterThan: "0" }
        }
      ) {
        totalCount
        nodes {
          id
          unitPrice
          currency {
            image
            name
            id
            decimals
            symbol
          }
        }
      }
      currencySales: sales(filter: { expiredAt: { greaterThan: $now } }) {
        aggregates {
          distinctCount {
            currencyId
          }
        }
      }
      creator {
        address
        name
        image
        verification {
          status
        }
      }
    }
  }
}
