query FetchExploreUsers(
  $limit: Int!
  $offset: Int!
  $orderBy: [AccountsOrderBy!]
  $filter: [AccountFilter!]
) {
  users: accounts(
    first: $limit
    offset: $offset
    orderBy: $orderBy
    filter: { isImported: { equalTo: false }, and: $filter }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      username
      address
      image
      cover
      name
      verification {
        status
      }
    }
  }
}
