query ChainCurrencies($filter: CurrencyFilter) {
  currencies(orderBy: CREATED_AT_ASC, filter: $filter) {
    nodes {
      id
      chainId
      address
      decimals
      symbol
      name
      image
    }
  }
}
