query GetAssetDataForRefresh(
  $chainId: Int!
  $collectionAddress: Address!
  $tokenId: String!
) {
  asset(
    chainId: $chainId
    collectionAddress: $collectionAddress
    tokenId: $tokenId
  ) {
    chainId
    collectionAddress
    tokenId
    updatedAt
  }
}

mutation RefreshAsset(
  $chainId: Int!
  $collectionAddress: Address!
  $tokenId: String!
) {
  refreshAsset(
    input: {
      chainId: $chainId
      collectionAddress: $collectionAddress
      tokenId: $tokenId
    }
  ) {
    clientMutationId
  }
}
