query GetAssetDataForRefresh($assetId: String!) {
  asset(id: $assetId) {
    chainId
    collectionAddress
    tokenId
    updatedAt
  }
}

mutation RefreshAsset($assetId: String!) {
  refreshAsset(input: { assetId: $assetId }) {
    clientMutationId
  }
}
