query SearchCollection(
  $filter: CollectionFilter!
  $limit: Int!
  $offset: Int!
) {
  collections(
    orderBy: TOTAL_VOLUME_DESC
    first: $limit
    filter: $filter
    offset: $offset
  ) {
    pageInfo {
      hasNextPage
    }
    nodes {
      chainId
      address
      name
      cover
      image
      totalVolume {
        refCode
        valueInRef
      }
      floorPrice {
        refCode
        valueInRef
      }
    }
  }
}
