query SearchCollection(
  $filter: CollectionFilter!
  $limit: Int!
  $cursor: Cursor
) {
  collections(
    orderBy: TOTAL_VOLUME_DESC
    first: $limit
    filter: $filter
    after: $cursor
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      chainId
      address
      name
      cover
      image
      totalVolume {
        refCode
        valueInRef
      }
      floorPrice {
        refCode
        valueInRef
      }
    }
  }
}
