query NavbarAccount($account: Address!, $lastNotification: Datetime!) {
  account(address: $account) {
    address
    name
    image
    notifications(
      filter: { createdAt: { greaterThan: $lastNotification } }
      includeWhenCollectionDeleted: YES
      includeWhenTradeDeleted: YES
    ) {
      totalCount
    }
  }
}
