query NavbarAccount($account: Address!, $lastNotification: Datetime!) {
  account(address: $account) {
    address
    name
    image
  }
  notifications(
    condition: { after: $lastNotification }
    includeWhenCollectionDeleted: YES
    includeWhenTradeDeleted: YES
  ) {
    totalCount
  }
}
