query FetchUserTradePurchased(
  $limit: Int!
  $offset: Int!
  $orderBy: [TradesOrderBy!]
  $address: Address!
) {
  trades(
    orderBy: $orderBy
    first: $limit
    offset: $offset
    filter: { buyerAddress: { equalTo: $address } }
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    nodes {
      transactionHash
      timestamp
      buyerAddress
      sellerAddress
      seller {
        address
        name
        image
        verification {
          status
        }
      }
      amount
      quantity
      currency {
        name
        image
        id
        decimals
        symbol
      }
      asset {
        id
        chainId
        collectionAddress
        tokenId
        name
        image
      }
    }
  }
}
